### PR TITLE
[第1組] Refactor naming conventions across backend APIs

### PR DESCRIPTION
**Pull request by mlcp29th-hi**
### Purpose

The purpose of this PR is to refactor the backend code to make it more readable and maintainable. The focus of the refactoring is to improve naming conventions to comply with PEP 8 guidelines and to reference recommendations from various sources, particularly emphasizing that code should be easy to read and consistent.

### Changes

Correct various abbreviations, typos, and vague terms such as `info`, `data`, and `result`, while also renaming functions, parameters, and classes to enhance readability and consistency. Many variables and functions used for conditional checks will be named in the form of `is_password_corrent()`, `does_user_upvote`, and `is_upvoted`. For APIs exposed to the public, GET methods will all begin with `read_`, while POST methods will start with a `verb`.

| Function Name (Original)          | Function Name (Refactored)    | Reasons of Changes |
|-----------------------------------|-------------------------------|--------------------|
| add_new                           | save_news                     | Replaced `add` with `save` to clarify that the operation is persistent.  |
| get_new_info                      | fetch_news_snapshots          | This function fetches news snapshots with keywords from an external website. |
| get_new                           | download_price_changes_news   | This function does not return a value; instead, it focuses on news about price changes and saves it to the database. |
| verify                            | is_password_correct           | This function returns a boolean value indicating whether the password is correct. |
| check_user_password_is_correct    | retrieve_user_by_credentials  | Rather than returning a boolean value, this function returns the `User` object if the provided credentials are valid. |
| authenticate_user_token           | retrieve_user_by_access_token | Rather than returning a boolean value, this function returns the `User` object if the provided access token is valid. |
| create_user                       | register_user                 | To indicate that new users will be added to the database, maintaining consistency with the API endpoint. |
| get_article_upvote_details        | get_upvote_status             | Improved consistency by using the term `news` to refer to the same concept. |
| news_summary                      | summarize_news                | Renamed with a verb to maintain consistency with other POST methods. |
| upvote_article                    | upvote_news                   | Improved consistency by using the term `news` to refer to the same concept. |
| news_exists                       | does_news_exist               | Clarified the semantics to indicate that the function returns a boolean value. |
| get_necessities_prices            | read_necessities_prices       | Renamed with the prefix `read_` to maintain consistency with other GET methods. |

### CODE REVIEW

**Comment by siangting** [comment]
The comment on the PR is excellent.

**Comment by Steven0811** [comment]
The well-structured comment on the PR makes me easy to understand what variables' names have been refactored. It seems like there are still some magic numbers not being extracted, such as 50 and 200 in lines 41 and 42.

**Comment by WANG-YongLE** [comment]
建議：
刪除171~172 行的迴圈
483行的id改成newsid
有些function的名稱我覺得沒有更動的必要性，只是讓看的人多看／檢查了幾行code

**Comment by kevin0216** [comment]
PR的comment結構良好，易於了解修改的地方。以下是幾點建議:
- 第227行的 messages 會建議再調整成更明確的名字，由於他是下給 LLM 的 Prompt，我認為可以修改成如 ai_prompt / prompt 等名字
- 第516行的 news_exists 中 argument "id" 容易與 Python 內建方法衝突，建議修改為其他名稱 (如 news_id)

**Comment by Yi-Cheng-Wang** [comment]
**Evaluation:**
- High degree of variable refactoring
- Variable renaming is very well done
- Code layout is very neat
- Commits are a bit messy and used force-pushed
- PR is very clear

**Suggestions:**
- Magic numbers seem to be left unaddressed; for example, the value `1892dhianiandowqd0n` on line 290 could be passed in a better way.
- The messages passed in different places are all called `messages`, but they have different functions and could be more clearly defined.

**Comment by mlcp29th-hi** [comment]
Hello @Steven0811,
> The well-structured comment on the PR makes me easy to understand what variables' names have been refactored. It seems like there are still some magic numbers not being extracted, such as 50 and 200 in lines 41 and 42.

Thank you for your reminder.

The reason I didn't extract the `50` and `200` in lines 41 and 42 is that **I don't perceive them as magic numbers in this scenario**.

As it mentioned during class, the `4` in the following code is a magic number whose meaning isn’t clear without additional context:
```java
public List<int[]> getThem() {
    List<int[]> list1 = new ArrayList<int[]>();
    for (int[] x: theList)
        if (x[0] == 4) // `4` is a magic number
            list1.add(x);
    return list1;
}
```
Extracting it as a variable or function can improve readability and maintainability.

However,  the `50` and `200` in lines 41 and 42 are different from the example above since we are creating an instance of `sqlalchemy.String`, whose initializer’s function signature indicates that the parameter is the length of the field.

Screenshot

In my opinion, there is enough context for people to easily understand that the line defines a column `username`, which is a string field with a length of 50 characters. Additionally, the values are only used in a single place, making extraction somewhat redundant.

**Comment by mlcp29th-hi** [comment]
嗨！ @lieofthehappiness 

> 建議： 刪除171~172 行的迴圈 483行的id改成newsid 有些function的名稱我覺得沒有更動的必要性，只是讓看的人多看／檢查了幾行code

由於這次 Pull Request 的目標是為了使函數變數的命名符合命名慣例，基於每個 PR 只做一件事情的原則，不應該刪除第171~172行的迴圈（修改程式邏輯）。此外，這段程式目的應該是想將 `snapshots_by_page` 中每個 page 取得的 `snapshots`（新聞快照列表）串在一起成為 `news_snapshots` 單一列表。

正確的寫法應該是使用 `list.extend(another_list)`：
```py
for snaptshots in snapshots_by_page:
    news_snapshots.extend(snaptshots)
```
而不是使用 `list.append(another_list)`，這樣會直接將整個 list 作為單一物件存入串列成為二維串列，依目前其他程式來看，這似乎不是呼叫者（`download_price_changes_news`、`search_news`）預期的結果：
```py
for snaptshots in snapshots_by_page:
    news_snapshots.append(snaptshots)
```
目前這段程式存在邏輯錯誤，但因為這次 PR 聚焦於命名慣例，相關的修改最好另開 PR 處理。

---

至於第 483 行的 `upvote_news(id)`，未將 `id` 更名為 `news_id`是因為根據函式名稱 `upvote_news` 已經知道它是為新聞按讚，`upvote_news(id)` 與 `upvote_news(news_id)` 相比，前者可提供相同的資訊卻更簡潔。

**更新**：`id` 是 Python 內建函式的名稱，確實改成 `news_id` 比較好。

---

關於您提到部分 function 的命名沒有更動的必要性，雖然不清楚是指哪個部分，若以 `read_necessities_prices` 為例，其原名為 `get_necessities_prices`，雖然不改似乎也不影響表達，但參考 localhost:8000/docs 可以發現程式其他所有的 GET method 都以 `read_` 命名，如同此 PR 將「可於本機立即取得結果」者以 `get_` 命名、「需自外部網路資源擷取資料」者以 `fetch_` 命名，目的都是為了**提高命名方式的一致性（Consistency）**。或者如有其他面向或具體 function 是這裡沒設想到的歡迎讓我們知道，感謝～

**Comment by mlcp29th-hi** [comment]
嗨！ @kevin0216 

> PR的comment結構良好，易於了解修改的地方。以下是幾點建議:
> 
> * 第227行的 messages 會建議再調整成更明確的名字，由於他是下給 LLM 的 Prompt，我認為可以修改成如 ai_prompt / prompt 等名字
> * 第516行的 news_exists 中 argument "id" 容易與 Python 內建方法衝突，建議修改為其他名稱 (如 news_id)

確實，像 `search_news` 裡面還用到 2 組不同目的 prompt，改成 `keyword_extraction_prompts`、`summary_generation_prompts` 的確更明瞭。參數 `id` 與 Python 內建函式名稱衝突的問題也確實應避免，感謝以上實用建議。

**Comment by mlcp29th-hi** [comment]
Hi @Yi-Cheng-Wang ,

> **Evaluation:**
> 
> * High degree of variable refactoring
> * Variable renaming is very well done
> * Code layout is very neat
> * Commits are a bit messy and used force-pushed
> * PR is very clear
> 
> **Suggestions:**
> 
> * Magic numbers seem to be left unaddressed; for example, the value `1892dhianiandowqd0n` on line 290 could be passed in a better way.
> * The messages passed in different places are all called `messages`, but they have different functions and could be more clearly defined.

Thank you for your feedback.

Exactly. The variables called `messages` are AI prompts for different purposes, and changing them to something like `keyword_extraction_prompts` and `summary_generation_prompts` might be a good idea.

---

As for the other points, I have some additional considerations:
* About the JWT secret key
1. There are definitely better ways to pass them into functions, but is it appropriate to include that kind of modification in this pull request?
2. At line 290, it’s easy to understand that `"1892dhianiandowqd0n"` is a JWT secret key by the parameter label `key=`.
```py
claims = jwt.decode(token, key='1892dhianiandowqd0n', algorithms=["HS256"])
```
3. Defining symbolic constants can help reduce duplication and enhance maintainability if certain values are repeated in multiple places. However, the key "1892dhianiandowqd0n" is only used twice, and it might be overkill to define it separately.

To sum up, **the key is to strike a balance between clarity and conciseness**. In my opinion, the current values have a context that is clear enough to convey their meaning. It would be better to keep them inline for now until those values are used in multiple places, in order to **avoid premature optimization**.

* About force push

Could you please provide a more specific reason for avoiding force pushes? Since I’m the only one working on this branch, I’m curious about how it impacts the workflow. Additionally, it is important to clean up your commits for a pull request; each commit should not be miscellaneous but concrete to help reviewers understand what changes have been made to achieve the goal. For instance, I believe reviewers may not want to track minor changes, such as typos that occurred during the branch, across multiple commits while focusing on the implementation of new features. Thank you!

**Review by taro0513 — COMMENTED** [review]
LGTM

**Pull request merged**
