### PR TITLE
[第1組] Refactor error handling and logging

### PR DESCRIPTION
**Pull request by mlcp29th-hi**
## Purpose
Improve error handling and logging with FastAPI [exception_handler](https://fastapi.tiangolo.com/tutorial/handling-errors/#override-the-httpexception-error-handler) and logging errors with sentry and logger.

### New Exceptions
1. NewsExtractionError
Raised when failed to parse HTML to `News` object.
2. LLMResponseFormatError
Raised when failed to parse the LLM's response to expected format.
3. NewsNotFoundError
Raised when the endpoint `api/v1/news/{news_id}/upvote` receiving a `news_id` where the news doesn't exist.
4. InvalidAccessTokenError
Raised when the user access token is invalid or expired.
5. InvalidCredentialsError
Raised when trying logging with the incorrect username or password.
6. UsernameNotAvailableError
Raised when trying registering a user where the username is already taken.

### Exception Handlers
1. `_authentication_error_handler`
2. `_registration_error_handler`
3. `_news_not_found_error_handler`
4. `_llm_response_format_error_handler`
5. `_domain_mismatch_exception_handler`

These exception handler are attached to FastAPI. FastAPI will catch the exceptions, and the handlers will be able to log them and generate appropriate response for clients.

```py
# src/user/exception_handlers.py
def _authentication_error_handler(request: Request, exception: AuthenticationError):
    capture_exception(exception)
    Logger().log_error(exception)
    return PlainTextResponse(exception.message, status_code=status.HTTP_401_UNAUTHORIZED)

def _registration_error_handler(request: Request, exception: RegistrationError):
    capture_exception(exception)
    Logger().log_error(exception)
    return PlainTextResponse(exception.message, status_code=status.HTTP_422_UNPROCESSABLE_ENTITY)

def attach_to(app: FastAPI):
    app.add_exception_handler(AuthenticationError, _authentication_error_handler)
    app.add_exception_handler(RegistrationError, _registration_error_handler)


# src/main.py
from user import exception_handlers as user_exception_handlers
user_exception_handlers.attach_to(app)
```

### CODE REVIEW

**Review by samlu00412 — COMMENTED** [review]
增加的error_handling跟logger除了可讀性高，且exception也有依照導入OOP的概念而非寫在一起，非常好的PR

**Comment by yozen0405** [comment]
這項實作有效地整合了強大的錯誤處理和日誌記錄機制，增強了系統的可靠性和可維護性。每個自訂例外處理，例如 NewsExtractionError、LLMResponseFormatError 和 InvalidAccessTokenError，都針對特定場景進行設計，提供了清晰且針對性的除錯能力。

**Comment by EdwardKYC** [comment]
為 user 和 llm_client 模組新增專門的例外類別，這是非常好的實踐。它有助於精準定位問題並提高可讀性，避免了過於籠統的 Exception 處理。

移除了模糊的 try-except 區塊，改用更具針對性的例外處理。
新增新聞 API 架構驗證和用戶表單驗證。

為爬蟲操作加入例外處理程序，確保在抓取過程出現異常時不會中斷系統流程

**Comment by patrickhicetc** [comment]
為各種功能都新增了額外的exceptions，讓可讀性增加。logger也清楚地記錄了各種錯誤和訊息

**Comment by Rogue8464** [comment]
一個很好的PR，透過OOP實作logger來整合不同的exception handler，並將錯誤處理應用於專案中，提高了程式運行的穩定性。

**Comment by Steven0811** [comment]
為各個router和service定義了各自的exception和handler，並且使用了OOP的概念，也加入了對於sqlalmchy跟requests相關的錯誤處理，另外還增加了針對error handling的unittest，我並沒有看到特別明顯的錯誤

**Comment by Yi-Cheng-Wang** [comment]
## Advantages

1. **Centralized Management**:
   The error handling logic is centralized in a dedicated `exception_handlers.py` file, making the code cleaner and easier to maintain and extend.

2. **Error Tracking with Sentry**:
   Using Sentry to capture exceptions allows real-time monitoring of errors in the production environment, providing detailed error reports, which are helpful for quickly locating issues.

3. **Custom Exception Classes**:
   Custom exception classes (such as `DomainMismatchException` and `NewsNotFoundError`) are defined, making it clearer to express the intent of errors. Specific error handling can be applied to different types of exceptions.

4. **HTTP Status Code Usage**:
   The system returns appropriate HTTP status codes (e.g., 404, 500) based on different error types, helping the client understand the nature of the error more clearly.

## Disadvantages

1. **Redundancy in Error Handling**:
   Similar error handling logic might exist across different modules, leading to code redundancy. Some common error handling logic could be extracted into base classes or utility functions.

2. **Lack of Detailed Error Information**:
   While exceptions are caught and errors are logged, the responses returned to users might lack sufficient context information, which can make it difficult for users to understand the root cause of the issue.

3. **Scope of Exception Handling**:
   The current error handling is mainly focused on specific exception types. Uncaught exceptions may cause application crashes or return unfriendly error messages. A general exception handler could be added to capture all uncaught exceptions.

4. **Performance Impact**:
   In high-traffic applications, excessive error capturing and logging, especially with Sentry, might impact performance by introducing additional delays.

## Summary

Overall, the error handling mechanism in this project is structurally sound and effectively captures and logs errors. However, there is room for improvement, particularly in reducing redundancy, providing more detailed error information, and enhancing general exception handling. These improvements will help increase the application's stability and enhance the user experience.

**Comment by Yuannzh1** [comment]
### 優點

1. **新增的 Try-Except 功能**：
   - 異常捕捉範圍明確，主要針對特定的異常類型進行處理，例如 `SQLAlchemyError`、`NewsExtractionError` 等。
   - 使用 `capture_exception` 紀錄異常，這有助於後續的錯誤追蹤和分析。
   - 將異常處理和業務邏輯分開，提高了程式碼的可讀性和可維護性。

2. **Logger 等級設定**：
   - 使用 `capture_exception` 紀錄異常，確保所有異常都被詳細記錄。
   - 將錯誤訊息日誌設定為 `error` 等級，確實反映了問題的嚴重性。

總結來說，改動的 Try-Except 功能和 Logger 等級設定大致合理，但可以通過在異常處理中添加更多的 `logger` 記錄來進一步提升日誌的詳細性和可追溯性。

**Comment by percykugood** [comment]
這個PR沒有太大的問題，將error handle和logger功能重構為集中化模組，提升code的可讀性與維護性，而且在過程中增加了詳細的錯誤訊息，幫助我們可以快速找到問題並提升系統的穩定性，整體符合Clean Code的原則，避免了多於的代碼並增強結構的一致性

**Comment by hamster0717** [comment]
### **Strengths**

1. **Improved Exception Handling:**
   - **Custom Exceptions:** Introduction of specific exceptions like `DomainMismatchException`, `NewsNotFoundError`, and `LLMResponseFormatError` improves the clarity and traceability of error conditions.
   - **Exception Handlers:** Centralized exception handling via functions like `_news_not_found_error_handler` and `_llm_response_format_error_handler` ensures uniform behavior and logging for related errors.
   - **Integration with Sentry:** Using `capture_exception` provides robust error tracking and visibility.

2. **Enhanced Logging:**
   - **Centralized Logger Class:** The new `Logger` class standardizes logging with shared instances, formatting, and support for file-based logging. This modular approach improves consistency across modules.
   - **Context-Specific Logging:** Logging messages in critical areas (e.g., scheduler, API responses) enhance observability for both development and production.

**Pull request merged**
