### PR TITLE
[第1組] Implement template methods for LLM clients

### PR DESCRIPTION
**Pull request by mlcp29th-hi**
# Purpose
Refactoring llm clients with Template Methods Patterns and ensuring the features of searching and summarizing news works well.

# Changes
## LLMClientBase
It follows the Singleton Pattern. The methods `extract_search_keyword`, `summarize_news`, and `evaluate_relevance` are changed to **abstract methods**. According to the TA's instructions, this base class defines what a client should be able to do, like a protocol.

## LLMClientTemplate
This class is the key to implement Template Methods Pattern. It inherits `LLMClientBase` and provides implementations of the following abstract methods:
1. `_ask(self, system_prompt: str, user_prompt: str) -> str | None:`
2. `extract_search_keywords(self, news_expectation: str) -> str | None`
3. `summarize_news(self, content: str) -> NewsSummary`
4. `evaluate_relevance_to_price_changes(self, news_title: str) -> RelevanceLevel`

It's a template defining how to extract search keyword, summarize news, and evaluate relevance by interacting with llm service. Additionally, it defines a static abstract method `_model() -> LLMClientModel`, which should be implemented by the subclasses to specify the provide and model of llm services.

## OpenAIClient and AnthropicClient

They inherits `LLMClientTemplate`. All they need to do is implementing `_model() -> LLMClientModel`, and the template methods pattern will do the rest.

The related environment variables are renamed or added so that `openai` and `anthropic` packages can read them automatically.

## Endpoint `/api/v1/news/news_summary_custom_model`
The new API makes it possible to choose between `openai` or `anthropic` to summarize the news content. The request schema is defined using Enum, ensuring that the backend receives either openai or anthropic; otherwise, it returns a 422 error. The testing of this endpoint with the two AI model options is covered in the integration tests.

## Others
* Refined the file structure by extracting the constants, schemas of llm client modules.
* Added the `@typing.override` decorator to indicate overriding the superclass's abstract methods.

### CODE REVIEW

**Comment by yozen0405** [comment]
這位同學的PR充分展現了專業與創意，透過 Template Method Pattern 簡化了 LLM 客戶端的擴展邏輯，並用 Singleton Pattern 優化資源管理。OpenAIClient 和 AnthropicClient 的設計高度模組化，API 的新增也兼顧靈活性與嚴謹性，Enum 的使用尤為亮眼。整體結構清晰，代碼整潔，不枉熬夜的努力！

**Comment by ptchen314** [comment]
### 值得肯定的部分
1. 架構設計
   - 正確運用Template Method Pattern重構LLM客戶端
   - Singleton Pattern的應用恰當
   - LLM寫得非常好，使我感覺抽象
### 需要改進的問題
1. 程式碼結構
   - LLMClientBase的怪抽象的
   - 老兄的扣蠻適合LLM inject

2. 文件
   - 你超會寫API文件
   - 環境變數說明呢(

### 必要修改項目
1. 寫一下API document la
2. 增加錯誤處理的測試案例
3. 補充架構設計文件，說明模式選擇的理由
4. 建議增加效能監控機制

這個PR整體品質十分甚至九分的好。

**Comment by Diego0923** [comment]
太強啦老哥!
清晰的抽象層次設計
良好的程式碼組織和完整的功能實作
或許可將 evaluate_relevance、generate_summary 等方法中的提示詞移至專門的模組
提升代碼可維護性與一致性。
總體來說，整體思路非常清晰，老哥不只是特乙
還是特強吧!

**Comment by Rogue8464** [comment]
這份PR十分的完美，展現了對軟工和OOP的理解，架構設計清晰且Template Method Pattern
 的應用簡化了LLM的API的擴展邏輯，OpenAIClient和AnthropicClient 的設計非常模組化，提高了代碼的可擴展性和一致性，還加強了靈活性和可維護性。

**Comment by Steven0811** [comment]
在base裡面定義並在template裡面覆寫展現出了OOP的基本概念，對於template的定義方式與在client內的使用情形都扣合著Template Methods Pattern的原則，在news_summary_with_custom_model端點的測試使用了mock_llm，而在mock_llm裡面有分別mock出OpenAIClient跟AnthropicClient也都符合作業對於此endpoint的要求

**Comment by percykugood** [comment]
這個PR有很好的架構思維和良好的設計水準，你利用 Template Method Pattern，展現出核心邏輯的模組化與抽象化，這樣減少code的複，也更容易未來擴展其他 LLM 客戶。整份code的整體結構很清晰，邏輯層次也很分明，有很多的錯誤處理，還加上Enum ，增加了可讀性。

**Comment by patrickhicetc** [comment]
整體程式碼簡潔且可讀性高，十分優秀
在`LLMClientBase`的`__new__`中使用到了Design Pattern的Singleton，做了個特別好的示範

**Comment by Yi-Cheng-Wang** [comment]
### Summary  
This code implements a language model client architecture based on abstract classes, providing several concrete implementations such as `OpenAIClient` and `AnthropicClient`. These implementations interact with different language models and offer features like keyword extraction, news summarization, and relevance assessment. The overall structure is clear, making it easy to expand and maintain.

### Strengths  
1. **Abstract Design**:  
   The use of the abstract base class `LLMClientBase` ensures that different client implementations follow a unified interface, facilitating expansion and replacement.  
2. **Clear Functional Division**:  
   Each method is well-defined with detailed documentation, making it easy to understand and use.  
3. **Use of Pydantic**:  
   Pydantic is used for data validation, ensuring data integrity and correctness.  
4. **Flexibility**:  
   New client implementations can be easily added, supporting various language models.

**Comment by EdwardKYC** [comment]
架構設計 正確運用Template Method Pattern重構LLM客戶端
整體程式碼簡潔且可讀性高，十分優秀
太強啦老哥!

**Comment by Yuannzh1** [comment]
整份PR清晰易懂，與其良好的組織和完整的功能實作，加上程式碼簡潔且可讀性高，屬實無可挑剔。

**Pull request merged**
